### ISSUE TITLE
User can checkout on shopify after clicking buy button

### ISSUE THREAD

**Issue by Kenny1G** [42techpacks/42-plus#31]
![Untitled (Draft)-1.jpg](https://uploads.linear.app/1c08417d-5c86-47a2-84fd-06250cd93955/4ac8cc21-a15e-41b1-88f6-298d97619df5/279e6bf2-2a54-47a4-b222-4c809e883180?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjMDg0MTdkLTVjODYtNDdhMi04NGZkLTA2MjUwY2Q5Mzk1NS80YWM4Y2MyMS1hMTVlLTQxYjEtODhmNi0yOThkOTc2MTlkZjUvMjc5ZTZiZjItMmE1NC00N2E0LWIyMjItNGM4MDllODgzMTgwIiwiaWF0IjoxNzIyNDY4MTA1LCJleHAiOjMzMjkzMDI4MTA1fQ.Q9mpgnB78eMaAs0cT06RUIVSsPbuh94qzyscjNlDgig "=1668x")

# TODO

- [X] ~~USER clicks buy now~~
- [X] ~~42+ requests checkout URL~~
- [X] ~~SHOPIFY gives checkout URL~~
- [X] ~~42+ updates DB with last checkout~~
  - [X] ~~get cart id from shopify~~
  - [X] ~~add new column to table~~
  - [X] ~~add cart id~~
- [X] ~~42+ redirects user to checkout~~
- [X] ~~USER completes purchase~~
- [X] EDGE FUNC subscribes to webhook and updates DB with user order
  - [X] listens for post request from shopify
  - [ ] verifies request is from shopify
  - [X] updates DB with the order
- [X] SHOPIFY sends checkout updated webhook
  - [X] set up webhook on notifications to webhook.site
  - [X] set up webhook to edge function
    - [X] expose over ngrok
- [ ] 42+ User is linked to shopify
  - [ ] shopify_customer_ids table (so that anon can populate)
- [ ] USER sees notification indicating there's a new order
  - [ ] seen by user column on database
  - [ ] shopify handler function to query number of pending notifs

- [ ] Push to Prod

# Options

* create shopify app that "ships the product they won to 42+"
* **set up a supabase edge function that listens for a "order created" webhook and populates the database when user makes an order**
* use soon to be deprecated redirect functionality to redirect back to supabase using a URL endpoint that informs client app of reveal
* **write to db latest checkout id created by a user session.**
  * shopify should have a way to
  * on order create webhook, inform supabase db that order associated with checkout id cooked

# extra

* use checkout id to link the 42+ user with the customer profile
